allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  esbuild: ^0.25.12
minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.0'
  - '@better-auth/drizzle-adapter@1.7.0'
  - '@better-auth/kysely-adapter@1.7.0'
  - '@better-auth/memory-adapter@1.7.0'
  - '@better-auth/mongo-adapter@1.7.0'
  - '@better-auth/prisma-adapter@1.7.0'
  - '@better-auth/telemetry@1.7.0'
  - better-auth@1.7.0
